export const asideSections = [
  {
    key: "works" as const,
    num: "01",
    ofTotal: "of 06",
    label: "Selected works",
    heading: "A focused body of <em>real</em>&nbsp;work.",
    desc: "Branding, launch strategy, and growth marketing for Ethiopian startups and digital businesses.",
    progressLabel: "Section progress",
    progressRange: ["2023", "2026"],
  },
  {
    key: "services" as const,
    num: "02",
    ofTotal: "of 06",
    label: "Services",
    heading: "Four <em>focused</em> services. One goal.",
    desc: "We make brands that work in the market \u2014 and marketing that works for the brand.",
    progressLabel: "Service type",
    progressRange: ["Brand", "Marketing"],
  },
  {
    key: "process" as const,
    num: "03",
    ofTotal: "of 06",
    label: "Process",
    heading: "Four phases. <em>No surprises.</em>",
    desc: "Most projects run about 4 weeks, broken into clear gates. You see progress weekly, not monthly.",
    progressLabel: "Average duration",
    progressRange: ["1 wk", "4 wks"],
  },
  {
    key: "why" as const,
    num: "04",
    ofTotal: "of 06",
    label: "Six reasons founders <em>choose us.</em>",
    heading: "Ethiopian market knowledge, clear process, and marketing that actually works.",
    desc: "Every project is shaped to feel considered from first brief to final handoff \u2014 no recycled templates, no rushed work.",
    progressLabel: "Client satisfaction",
    progressRange: ["100% Ethiopian market focus"],
  },
  {
    key: "words" as const,
    num: "05",
    ofTotal: "of 06",
    label: "Testimonials",
    heading: "In <em>their words.</em>",
    desc: "Notes from the founders and teams we\u2019ve worked with.",
    progressLabel: "Section progress",
    progressRange: ["From recent projects"],
  },
  {
    key: "contact" as const,
    num: "06",
    ofTotal: "of 06",
    label: "Get in touch",
    heading: "Tell us <em>about it.</em>",
    desc: "Whether it\u2019s a full rebrand or a growth marketing campaign, we\u2019d love to hear what you\u2019re building. We reply to every brief.",
    progressLabel: "Booking window",
    progressRange: ["From Aug 2026"],
  },
] as const;

export type AsideKey = (typeof asideSections)[number]["key"];
